use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# EfossilsWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :efossils, EfossilsWeb.Endpoint,
  load_from_system_env: true,
  http: [port: {:system, "PORT"}],
  url: [host: "localhost", port: {:system, "PORT"}],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true,
  root: ".",
  version: Application.spec(:phoenix_distillery, :vsn)

config :efossils,
  ecto_repos: [Efossils.Repo],
  federated_name: System.get_env("EFOSSILS_FEDERATED_NAME"),
  fossil_bin: System.get_env("EFOSSILS_FOSSIL_BIN"),
  fossil_base_url: System.get_env("EFOSSILS_FOSSIL_BASE_URL"),
  fossil_repositories_path: System.get_env("EFOSSILS_REPOSITORY_PATH"),
  fossil_work_path: System.get_env("EFOSSILS_WORK_PATH"),
  fossil_user_admin: "efossils_admin",
  fossil_mirror_ticktime: String.to_integer(System.get_env("EFOSSILS_MIRROR_TICKTIME") || "600000"),
  email_from_name: System.get_env("EFOSSILS_EMAIL_FROM_NAME"),
  email_from_email: System.get_env("EFOSSILS_EMAIL_FROM_EMAIL")

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :efossils, EfossilsWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [:inet6,
#               port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :efossils, EfossilsWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :efossils, EfossilsWeb.Endpoint, server: true
#

# Finally import the config/prod.secret.exs
# which should be versioned separately.
import_config "prod.secret.exs"
